from colorama import Fore

def helping():
    print()
    print(Fore.CYAN + "******** HELP MENU *********" + Fore.RESET)
    print(Fore.RED + "Open Applications:" )
    print(Fore.RED + "Text Editor(Notepad)")
    print(Fore.RED + "VS Code")
    print(Fore.RED + "Chrome")
    print(Fore.RED + "Open Random Mini Games" )
    print(Fore.RED + "Play Songs")
    print(Fore.RED + "Play Music")
    print(Fore.RED + "Send whatsapp msg")
    print(Fore.RED + "Send Email")
    print(Fore.RED + "Send Text Msg")
    print(Fore.RED + "Open any website")
    print(Fore.RED + "Open Calculator")
    print(Fore.RESET)
    print(Fore.CYAN + "I can help you with above things" + Fore.RESET)
    print()